spring.application.name=blog
spring.mongodb.uri = mongodb+srv://mksnitc_db_user:m130289ca@cluster0.ccqthig.mongodb.net/?appName=Cluster0
spring.mongodb.database=blogdb
spring.data.mongodb.auto-index-creation=true
