spring.application.name=blog
spring.mongodb.uri = mongodb+srv://mksnitc_db_user:m130289ca@cluster0.ccqthig.mongodb.net/?appName=Cluster0
spring.mongodb.database=blogdb
spring.data.mongodb.auto-index-creation=true
jwt.secret=change-this-secret-key-to-a-long-random-value-at-least-32-characters
jwt.expiration=86400000
spring.jackson.deserialization.fail-on-unknown-properties=true